server:
  port: ${TRADING_SERVER_PORT:8085}

spring:
  config:
    import:
      - optional:file:tradingMicroService/tradingmicroservice/.env[.properties]
      - optional:file:tradingmicroservice/.env[.properties]
      - optional:file:.env[.properties]

  application:
    name: ${TRADING_APPLICATION_NAME:TRADING-SERVICE}

  datasource:
    url: ${TRADING_DB_URL:jdbc:mysql://localhost:3306/mydb}
    driver-class-name: ${TRADING_DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${TRADING_DB_USERNAME:root}
    password: ${TRADING_DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${TRADING_JPA_DDL_AUTO:update}
    show-sql: ${TRADING_JPA_SHOW_SQL:true}

eureka:
  client:
    register-with-eureka: ${TRADING_EUREKA_REGISTER:true}
    fetch-registry: ${TRADING_EUREKA_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${TRADING_EUREKA_URL:http://localhost:8080/eureka/}
  instance:
    hostname: ${TRADING_EUREKA_HOSTNAME:localhost}
