server:
  port: ${GATEWAY_SERVER_PORT:8081}

spring:
  config:
    import:
      - optional:file:APIGateway/apigateway/.env[.properties]
      - optional:file:apigateway/.env[.properties]
      - optional:file:.env[.properties]

  application:
    name: ${GATEWAY_APPLICATION_NAME:WTMS-GATEWAY}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: USER-SERVICE
                    fallbackuri: forward:/userFallback

            - id: BANK-SERVICE
              uri: lb://BANK-SERVICE
              predicates:
                - Path=/bank/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: BANK-SERVICE
                    fallbackuri: forward:/bankFallback

            - id: PORTFOLIO-SERVICE
              uri: lb://PORTFOLIO-SERVICE
              predicates:
                - Path=/portfolio/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: PORTFOLIO-SERVICE
                    fallbackuri: forward:/portfolioFallback

            - id: TRADING-SERVICE
              uri: lb://TRADING-SERVICE
              predicates:
                - Path=/trading/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: TRADING-SERVICE
                    fallbackuri: forward:/tradingFallback

            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: PRODUCT-SERVICE
                    fallbackuri: forward:/productFallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
  timelimiter:
    configs:
      default:
        timeout-duration: ${GATEWAY_TIMEOUT_DURATION:5s}

eureka:
  client:
    register-with-eureka: ${GATEWAY_EUREKA_REGISTER:true}
    fetch-registry: ${GATEWAY_EUREKA_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${GATEWAY_EUREKA_URL:http://localhost:8080/eureka/}
  instance:
    hostname: ${GATEWAY_EUREKA_HOSTNAME:localhost}


springdoc:
  # Path for the interactive Swagger UI HTML page
  swagger-ui:
    path: ${GATEWAY_SWAGGER_UI_PATH:/swagger-ui.html}
    operations-sorter: alpha # Sorts endpoints alphabetically
    tags-sorter: alpha       # Sorts tags/controllers alphabetically

  # Path for the raw OpenAPI JSON specification
  api-docs:
    path: ${GATEWAY_API_DOCS_PATH:/v3/api-docs}
